### ISSUE TITLE
{elapsed_time} is not showing 

### ISSUE THREAD

**Issue by ngangchill** [ozziest/ci-starter#1]
with blade template, it shows the pseudovariable '{elapsed_time}' not the actual execution time.

please help...

**Comment by ozziest** [comment]
Remove following line from `app/views/welcome_message.blade.php`;

```php 
<p class="footer">Page rendered in <strong>{elapsed_time}</strong> seconds</p>
```

**Comment by ngangchill** [comment]
if i do that how i will show elapsed time ??

**Comment by ozziest** [comment]
I have changed some of parts. Now, you can call the elapsed time like this;

```php 
<p class="footer">Page rendered in <strong>{{ $elapsed_time }}</strong> seconds</p>
```

But you need a new install for your project or you should add this part to method of the file that call "app/App/View.php";

```php
    public function make($file, $arguments = array())
    {
        $ci =& get_instance();
        $ci->benchmark->mark('code_end');
        $arguments['elapsed_time'] = $ci->benchmark
            ->elapsed_time('total_execution_time_start', 'code_end');
        echo $this->engine->view()->make($file, $arguments);
    }
```

**Comment by ngangchill** [comment]
thanks :-)
